-- AlterTable
ALTER TABLE `cases` ADD COLUMN `department` ENUM('FIRST_COLLECTION', 'SECOND_COLLECTION', 'QUARANTINE') NOT NULL DEFAULT 'FIRST_COLLECTION',
    ADD COLUMN `status` ENUM('IN_COLLECTION', 'COLLECTION_FINISHED') NOT NULL DEFAULT 'IN_COLLECTION';
